---
title: "Project Proposal"
author: "Regression Rockstars - James Cai, Steph Reinke, Sarah Wu, Michael Zhou"
format: pdf
execute: 
  warning: false
  message: false
editor: visual
---

```{r}
#| label: load-pkg-data
#| warning: false
#| message: false
library(tidyverse)
library(tidymodels)
library(knitr) 
library(patchwork)
# add other packages as needed

scoobydoo <- read_csv("data/Scooby-Doo Completed.csv")
```

## Introduction

Scooby-Doo is a popular animated TV show that follows a group of teenagers and a talking Great Dane, Scooby-Doo, as they solve mysteries involving supernatural monsters and creatures. Each episodes typically involves seeking and scheming to find the villain, ending with a dramatic unmasking of the monster. The show focuses on themes of friendship and teamwork. The show aired from 1969 - 1976 originally with many subseires airing and reruns.

We are interested in researching Scoody-Doo IMBD ratings because we all enjoyed Scooby-Doo in our childhoods. We also think that finding certain predictors of animated TV series ratings is useful for the entertainment industry. Specifically anyone looking to create an animated TV series and wanting to know what aspects make up a successful episode. If Scooby-Doo continues to create spin off shows, this information could inform their future episodes.

What factors explain the variability in the IMBD scores of the Scooby-Doo episodes?

We want to investigate how monster_amount, engagement, and who unmasked the villain (unmask_fred, and so on for all the main group) adequately explain the variability of the IMBD rating. We think that the more monsters the better the rating will be because we think there is more action and suspense in episodes with more monsters. We also think that the higher engagement the worse the rating will be because we think that people are more likely to write a review online when they do not like something than if they do. We think that episodes where Fred unmasked the villian will have a higher rating because we think that he is the leader of the group and thus we think that people will be more drawn to him.

## Data description

sds...

## Initial exploratory data analysis

...

## Analysis approach

...

## Data dictionary

The data dictionary can be found [here](ADD%20LINK!!!) \[Update the link and remove this note!\]
